
[[mouse.bindings]]
action = "Copy"
mods = "Shift"
mouse = "Left"

[[mouse.bindings]]
action = "Paste"
mods = "Shift"
mouse = "Right"

[general]
live_config_reload = true
import = ["/Users/tsuyoshihara/.config/alacritty/color-schemes/iceberg.toml"]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen Console NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 2

[font.italic]
family = "HackGen Console NF"
style = "Italic"

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[font.offset]
x = 0
y = 2

[window]
decorations = "Buttonless"
opacity = 0.99
startup_mode = "Windowed"

[window.padding]
x = 4
y = 0

[mouse]
