tap "datawire/blackbird"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "ktr0731/evans"
tap "rerost/tools"
tap "sanemat/font"
tap "teamookla/speedtest"
tap "uzimaru0000/tap"
tap "wantedly/tools", "git@github.com:wantedly/homebrew-tools"
tap "yoheimuta/protolint"
brew "python@3.10", link: false
brew "awscli", link: false
brew "glib"
brew "python@3.9"
brew "tcl-tk"
brew "deno"
# brew "dep"
brew "diff-so-fancy"
brew "direnv"
brew "envchain"
brew "exa"
brew "fd"
brew "gobject-introspection"
brew "harfbuzz"
brew "pango"
brew "fontforge"
brew "fzf"
brew "gdk-pixbuf"
brew "little-cms2"
brew "openjpeg"
brew "git"
brew "goenv"
brew "librsvg"
brew "graphviz"
brew "htop"
brew "imagemagick@6", link: false 
brew "jq"
brew "node-build"
brew "nodenv"
brew "openjdk"
brew "openjdk@11"
brew "protobuf"
brew "pstree"
brew "python-yq"
brew "python@3.8", link: false
brew "ruby-build"
brew "rbenv"
# brew "redis@3.2", restart_service: true
brew "ripgrep"
brew "shared-mime-info"
brew "stow"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "watch"
brew "yarn"
brew "datawire/blackbird/telepresence", link: false
brew "ktr0731/evans/evans"
brew "rerost/tools/giro"
# brew "sanemat/font/ricty", args: ["with-powerline"]
brew "teamookla/speedtest/speedtest"
brew "uzimaru0000/tap/tv"
# brew "yoheimuta/protolint/protolint"
cask "chromedriver"
cask "docker"
cask "font-hackgen"
cask "font-hackgen-nerd"
# cask "graphiql"
# cask "hyperswitch"
# cask "insomnia"
cask "iterm2"
cask "keycastr"
# cask "osxfuse"

