#!/bin/zsh

set -eux
set -o pipefail

# emulate GNU readlink's "readlink -f" behavior on Mac
# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
TARGET_FILE=$0

cd `dirname $TARGET_FILE`
TARGET_FILE=`basename $TARGET_FILE`

# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done

# Compute the canonicalized name by finding the physical path 
# for the directory we're in and appending the target file.
BASE_DIR=`pwd -P`
# PHYS_DIR=`pwd -P`
# RESULT=$PHYS_DIR/$TARGET_FILE
# echo $RESULT
# echo $(dirname $RESULT)
# BASE_DIR=$(dirname $RESULT)

function install_zprezto()
{
    # https://github.com/sorin-ionescu/prezto#installation
    git clone --recursive https://github.com/sorin-ionescu/prezto.git $HOME/.zprezto

    setopt EXTENDED_GLOB
    for rcfile in $HOME/.zprezto/runcoms/^README.md(.N); do
        ln -s "$rcfile" "$HOME/.${rcfile:t}"
    done

    # chsh -s /bin/zsh
}

function run_stow()
{
    if type stow > /dev/null 2>&1; then
        echo "Making symlinks of dot files..."
        echo

        stow -vvv git tmux vim zsh starship

        echo
        echo "🎉 Done!"
        echo
    else
        echo "Install stow first!"
    fi
}

function extend_zshrc()
{
    echo "Load .zshrc-extend from .zshrc"
    echo

    set +e
    RES=$(grep "source \$HOME/dotfiles/config/.zshrc-extend" $HOME/.zshrc)

    echo ${RES}
    if [ "${RES}" = "" ]; then
        echo "\"source \$HOME/dotfiles/config/.zshrc-extend\" >> $HOME/.zshrc"
        echo "source \$HOME/dotfiles/config/.zshrc-extend" >> $HOME/.zshrc
    fi
    echo
    echo "🎉 Done!"
    echo
    set -e
}

function install_homebrew()
{
  # Install Homebrew
  if type brew > /dev/null 2>&1; then
    echo 'Homebrew has already been installed.'
  else
    echo 'Install Homebrew'
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
  fi

  echo "brew bundle"
  brew bundle
}

function main()
{
    case $1 in
        "zprezto")
            install_zprezto
            ;;
        "dot" | "dots" | "stow")
            run_stow
            ;;
        "extend-zshrc")
            extend_zshrc
            ;;
        "brew")
            install_homebrew
            ;;
        *)
            install_homebrew
            install_zprezto
            make_dot_files_symlinks
            extend_zshrc
            ;;
    esac
}

main ${1:-""}

