#!/bin/zsh

set -eux
set -o pipefail

# emulate GNU readlink's "readlink -f" behavior on Mac
# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
TARGET_FILE=$0

cd `dirname $TARGET_FILE`
TARGET_FILE=`basename $TARGET_FILE`

# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done

# Compute the canonicalized name by finding the physical path 
# for the directory we're in and appending the target file.
BASE_DIR=`pwd -P`
# PHYS_DIR=`pwd -P`
# RESULT=$PHYS_DIR/$TARGET_FILE
# echo $RESULT
# echo $(dirname $RESULT)
# BASE_DIR=$(dirname $RESULT)

function install_zprezto()
{
    # https://github.com/sorin-ionescu/prezto#installation
    git clone --recursive https://github.com/sorin-ionescu/prezto.git $HOME/.zprezto
    # chsh -s /bin/zsh
}

function run_stow()
{
    if type stow > /dev/null 2>&1; then
        echo "Making symlinks of dot files..."
        echo

        stow -R -vvv \
          alacritty \
          bat \
          gh \
          git \
          nvim \
          starship \
          tmux \
          vim \
          zsh

        stow -R -vvv -t "$HOME/Library/Application Support/Code/User" vscode
        stow -R -vvv -t "$HOME/Library/Application Support/Cursor/User" cursor
        stow -R -vvv -t "$HOME/.claude" claude

        if [ ! -d $HOME/scripts ]; then
            mkdir $HOME/scripts
        fi
        stow -R -vvv -t "$HOME/scripts" scripts

        echo
        echo "🎉 Done!"
        echo
    else
        echo "Install stow first!"
    fi
}

function install_homebrew()
{
  # Install Homebrew
  if type brew > /dev/null 2>&1; then
    echo 'Homebrew has already been installed.'
  else
    echo 'Install Homebrew'
    # https://brew.sh
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    brew update
  fi

  echo "brew bundle"
  brew bundle
}

function install_global_npm_packages()
{
  if type yarn > /dev/null 2>&1; then
    # yarn global list
    yarn global add \
        create-next-app \
        git-delete-squashed \
        git-split-diffs \
        npkill \
        # prettierd \
        yarn-deduplicate
  else
    echo 'Install yarn first!'
  fi
}

function install_tmux_plugins()
{
  if type tmux > /dev/null 2>&1 ; then
    if [ -d ~/.tmux/plugins/tpm ]; then
      echo 'tpm is already installed!'
    else
      echo 'install tpm'
      # https://github.com/tmux-plugins/tpm
      git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm

      echo 'Create tmux session and run the following command in the session.'
      echo 'prefix + I (ctrl + t → I)'
    fi
  else
    echo 'Install tmux first!'
  fi
}

function main()
{
    case $1 in
        "zprezto")
            install_zprezto
            ;;
        "dot" | "dots" | "stow")
            run_stow
            ;;
        "brew")
            install_homebrew
            ;;
        "npm" | "yarn")
            install_global_npm_packages
            ;;
        "tmux")
            install_tmux_plugins
            ;;
        *)
            install_homebrew
            install_zprezto
            make_dot_files_symlinks
            install_global_npm_packages
            install_tmux_plugins
            ;;
    esac
}

main ${1:-""}

