# https://www.nerdfonts.com/cheat-sheet
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# gray_light="#d8dee9"
# gray_medium="#abb2bf"
# gray_dark="#3b4252"
# green_soft="#a3be8c"
# blue_muted="#81a1c1"
# cyan_soft="#88c0d0"

format = """
[░▒▓](#292929)\
$directory\
[](fg:#292929 bg:#3b4252)\
$git_branch\
$git_status\
[](fg:#3b4252)\
$custom\
$fill\
[](fg:#a3aed2)\
$time\
[▓▒░](#a3aed2)\
\n$character"""

[character]
success_symbol = '[➜](bold #a3be8c)'
error_symbol = '[➜](bold #bf616a)'

[directory]
style = "fg:#d8dee9 bg:#292929"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3b4252"
format = '[[ $symbol $branch ](fg:#f5f5f5 bg:#3b4252)]($style)'

[git_status]
style = "bg:#394260"
conflicted = '! '
# stashed = '󰄠 '
stashed = ''
staged = ' '
modified = '✻ '
renamed = '» '
deleted = " "
format = '[[($all_status$ahead_behind)](fg:#f5f5f5 bg:#394260)]($style)'

[fill]
symbol = ' '

[time]
disabled = false
time_format = "%T" # Hour:Minute:Second
style = "bg:#1d2230"
format = '[[ $time ](fg:#292929 bg:#a3aed2)]($style)'

[custom.wtd-fork-qa]
command = 'echo fork qa' # shows output of command
when = ''' test $KUBE_FORK_TARGET_ENV = "qa" '''
format = ' [[$output](fg:#ff9900)]($style)'

[custom.wtd-fork-sb]
command = 'echo fork sb' # shows output of command
when = ''' test $KUBE_FORK_TARGET_ENV = "sandbox" '''
format = ' [[$output](fg:#c52587)]($style)'
