# https://www.nerdfonts.com/cheat-sheet
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Polar Night
# nord0: #2e3440
# nord1: #3b4252
# nord2: #434c5e
# nord3: #4c566a

# Snow Storm
# nord4: #d8dee9
# nord5: #e5e9f0
# nord6: #eceff4

# Frost
# nord7: #8fbcbb
# nord8: #88c0d0
# nord9: #81a1c1
# nord9: #5e81ac

# Aurora
# nord10: #bf616a red
# nord11: #d08770 orange
# nord12: #ebcb8b yellow
# nord13: #a3be8c green
# nord14: #b48ead purple

format = """
[░▒▓](#bf616a)\
$directory\
[](fg:#bf616a bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A)\
$custom\
$fill\
$ruby\
$nodejs\
[](fg:#4c566a)\
$time\
[▓▒░](#4c566a)\
\n$character"""

[directory]
style = "fg:#eceff4 bg:#bf616a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol $branch ](fg:#f5f5f5 bg:#4c566a)]($style)'

[git_status]
style = "bg:#4C566A"
conflicted = '! '
# stashed = '󰄠 '
stashed = ''
staged = ' '
modified = '✻ '
renamed = '» '
deleted = " "
format = '[[($all_status$ahead_behind)](fg:#f5f5f5 bg:#4C566A)]($style)'

[fill]
symbol = ' '

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#3c873a)]($style)'

[ruby]
symbol = ""
format = '[[ $symbol ($version) ](fg:#e0115f)]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute:Second
style = "bg:#1d2230"
format = '[[ $time ](fg:#ECEFF4 bg:#4c566a)]($style)'

[custom.wtd-fork-qa]
command = 'echo fork qa' # shows output of command
when = ''' test $KUBE_FORK_TARGET_ENV = "qa" '''
format = ' [[$output](fg:#ff9900)]($style)'

[custom.wtd-fork-sb]
command = 'echo fork sb' # shows output of command
when = ''' test $KUBE_FORK_TARGET_ENV = "sandbox" '''
format = ' [[$output](fg:#c52587)]($style)'

