# https://www.nerdfonts.com/cheat-sheet

# [](fg:#394260 bg:#1d2230)\
format = """
[░▒▓](#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
$custom\
$fill\
$ruby\
$nodejs\
[](fg:#a3aed2)\
$time\
[▓▒░](#a3aed2)\
\n$character"""

[directory]
style = "fg:#292929 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[fill]
symbol = ' '

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#3c873a)]($style)'

[ruby]
symbol = ""
format = '[[ $symbol ($version) ](fg:#e0115f)]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute:Second
style = "bg:#1d2230"
format = '[[ $time ](fg:#292929 bg:#a3aed2)]($style)'

[custom.wtd-fork-qa]
command = 'echo fork qa' # shows output of command
when = ''' test $KUBE_FORK_TARGET_ENV = "qa" '''
format = ' [[$output](fg:#ff9900)]($style)'

[custom.wtd-fork-sb]
command = 'echo fork sb' # shows output of command
when = ''' test $KUBE_FORK_TARGET_ENV = "sandbox" '''
format = ' [[$output](fg:#c52587)]($style)'
